# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightBookingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FSCalendar'
  pod 'lottie-ios'

  target 'FlightBookingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
